{% set name = "prettier" %}
{% set version = "3.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 15c8bff7263cd6a523a39fcbfd117a3055266eb67416c0eb364f7ca9eb3e869e

build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - nodejs  # [not win]
    - m2w64-jq   # [win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"  # [not win]
    - prettier --version | findstr "{{ version }}"  # [win]
    - where prettier  # [win]

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - janjagusch
    - xhochy
    - pavelzw
