{% set name = "prettier" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2c88d1dfc2c43b06ab44dcc9d90eda56b0789d0ab0e65fa3797bc7eda81a0dc3

build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - nodejs  # [not win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"  # [not win]
    - prettier --version | findstr "{{ version }}"  # [win]
    - where prettier  # [win]

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
    - xhochy
    - pavelzw
    - JannikWibkerQC
