{% set name = "prettier" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: b003747ebcdf76e3bea75a987ee746fc16bd2a876716f73a4d8b167b6c5fa376

build:
  number: 0

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - nodejs  # [not win]
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"  # [not win]
    - prettier --version | findstr "{{ version }}"  # [win]
    - where prettier  # [win]

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
    - xhochy
