{% set name = "prettier" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 86c6af269a5d6e15924d8d718ceb534542549ab94d66deade740d1465fa89d79

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
