schema_version: 1

context:
  name: prettier
  version: "3.7.3"

package:
  name: ${{ name|lower }}
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/${{ version }}.tar.gz
  sha256: 4245b9bcef0f591de6397501f138a8ec5fb144a78e965dbe9d4917a9905b7858

build:
  number: 0

requirements:
  build:
    - ${{ stdlib("c") }}
    - if: not win
      then: nodejs
      else: m2w64-jq
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

tests:
  - script:
      - if: not win
        then: prettier --version | grep "${{ version }}"
        else:
          - prettier --version | findstr "${{ version }}"
          - where prettier
about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.
  homepage: https://github.com/prettier/prettier

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - janjagusch
    - xhochy
    - pavelzw
