schema_version: 1

context:
  name: prettier
  version: "3.6.1"

package:
  name: ${{ name|lower }}
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/${{ version }}.tar.gz
  sha256: d07230d5b8c563cc3582f889b426bdf875dc479b3e81655eb1936bdeba5d965d

build:
  number: 0

requirements:
  build:
    - ${{ stdlib("c") }}
    - if: not win
      then: nodejs
      else: m2w64-jq
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

tests:
  - script:
      - if: not win
        then: prettier --version | grep "${{ version }}"
        else:
          - prettier --version | findstr "${{ version }}"
          - where prettier
about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.
  homepage: https://github.com/prettier/prettier

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - janjagusch
    - xhochy
    - pavelzw
