schema_version: 1

context:
  name: prettier
  version: 3.5.3

package:
  name: ${{ name|lower }}
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/${{ version }}.tar.gz
  sha256: 8f1024abc4d797214e2c0e2a93a53f24c83729c973a0cf7d8d999cb1059daa70

build:
  number: 1

requirements:
  build:
    - ${{ stdlib("c") }}
    - if: not win
      then: nodejs
    - if: win
      then: m2w64-jq
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

tests:
  - script:
      - if: not win
        then: prettier --version | grep "${{ version }}"
      - if: win
        then: prettier --version | findstr "${{ version }}"
      - if: win
        then: where prettier

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.
  homepage: https://github.com/prettier/prettier

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - janjagusch
    - xhochy
    - pavelzw
